### PR TITLE
protect strings

### PR DESCRIPTION
**Pull request by pums974**
The linter should not change a string (issue #8)

This solution is not optimal

### CODE REVIEW

**Comment by cphyc** [comment]
Thanks for the PR. Unfortunately it seems the failing test seems real (`integer*4` should be changed into `integer(4)`).

**Comment by cphyc** [comment]
On a side note: you can run tests locally with pytest using `pytest tests/`.

**Comment by pums974** [comment]
Your main branch is failing this test, I forked from it hence I have the same issue

Once fixed in master, I'll update this PR

Le 22 mars 2021 19:41:25 GMT+01:00, Corentin Cadiou ***@***.***> a écrit :
>Thanks for the PR. Unfortunately it seems the failing test seems real
>(`integer*4` should be changed into `integer(4)`).
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cphyc/fortran-syntax/pull/9#issuecomment-804302560

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by cphyc** [comment]
My bad, that's right! I'll fix master as soon as possible (don't have much time on my plate at the moment).

**Comment by cphyc** [comment]
I think the string regexp should be
```regex
([\"'])(.*?[^\\]|)\1
```
instead of
```regex
([\"'])(?:\\\1|.)*?\1
```
The latter matches for example `y="foo\"`. What do you think?

**Comment by cphyc** [comment]
Actually I just realised that
```fortran
character(len=1000) :: string
string = "foo \" bar" ! This is invalid fortran
string = "foo "" bar" ! This is valid and contains the string `foo " bar`
```
The good news is that the following (slightly simpler) regexp seems to do the trick
```regexp
([\"']).*?\1
```

**Comment by cphyc** [comment]
Merging this, if you feel like I missed a corner case, don't hesitate to re-push on your branch on re-open.

**Comment by pums974** [comment]
No it's seems alright

thank you

**Pull request merged**
